inherit_from: .rubocop_todo.yml

Style/Documentation:
  Enabled: false

Style/NumericLiterals:
  Exclude:
    - 'db/schema.rb'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'db/schema.rb'

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/*'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'
