Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/*'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'

Style/FrozenStringLiteralComment:
  Enabled: false

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'vendor/**/*'
